---
# tasks file for mysql
- name: Create mysql database
  become: true
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Update mysql root password for all root accounts
  become: true
  mysql_user: name=root host={{ server_hostname }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost